# Generated by Django 2.2.6 on 2020-01-13 12:15

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=False, verbose_name='active_status')),
                ('date_active_ini', models.DateField(blank=True, null=True, verbose_name='date ini')),
                ('date_active_end', models.DateField(blank=True, null=True, verbose_name='date end')),
                ('description_short', models.TextField(blank=True, verbose_name='description short')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='name')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='category_service/', verbose_name='imagen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=False, verbose_name='active_status')),
                ('date_active_ini', models.DateField(blank=True, null=True, verbose_name='date ini')),
                ('date_active_end', models.DateField(blank=True, null=True, verbose_name='date end')),
                ('description_short', models.TextField(blank=True, verbose_name='description short')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='name')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='service/', verbose_name='imagen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecialisedUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=False, verbose_name='active_status')),
                ('date_active_ini', models.DateField(blank=True, null=True, verbose_name='date ini')),
                ('date_active_end', models.DateField(blank=True, null=True, verbose_name='date end')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='name')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='SpecialisedUnit/', verbose_name='imagen')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
