# Generated by Django 2.2.6 on 2020-01-13 14:39

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryservice',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='categoryservice',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='categoryservice',
            name='description_gl',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='categoryservice',
            name='description_pt',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='categoryservice',
            name='description_short_en',
            field=models.TextField(blank=True, null=True, verbose_name='description short'),
        ),
        migrations.AddField(
            model_name='categoryservice',
            name='description_short_es',
            field=models.TextField(blank=True, null=True, verbose_name='description short'),
        ),
        migrations.AddField(
            model_name='categoryservice',
            name='description_short_gl',
            field=models.TextField(blank=True, null=True, verbose_name='description short'),
        ),
        migrations.AddField(
            model_name='categoryservice',
            name='description_short_pt',
            field=models.TextField(blank=True, null=True, verbose_name='description short'),
        ),
        migrations.AddField(
            model_name='categoryservice',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='categoryservice',
            name='name_es',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='categoryservice',
            name='name_gl',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='categoryservice',
            name='name_pt',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_gl',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_pt',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_short_en',
            field=models.TextField(blank=True, null=True, verbose_name='description short'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_short_es',
            field=models.TextField(blank=True, null=True, verbose_name='description short'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_short_gl',
            field=models.TextField(blank=True, null=True, verbose_name='description short'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_short_pt',
            field=models.TextField(blank=True, null=True, verbose_name='description short'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_es',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_gl',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_pt',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='specialisedunit',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='specialisedunit',
            name='name_es',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='specialisedunit',
            name='name_gl',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='specialisedunit',
            name='name_pt',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='categoryservice',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='category_service/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='service.CategoryService', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='service/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='specialisedunit',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='SpecialisedUnit/', verbose_name='image'),
        ),
    ]
