"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from django.utils.translation import ugettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

from django.core.exceptions import ImproperlyConfigured

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get['SECRET_KEY']
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

INSTALLED_APPS = [

    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'bootstrap4',
    'widget_tweaks',
    'easy_thumbnails',
    'mptt',
    'leaflet',
    'django_mptt_admin',
    'django_summernote',

    'webpush',

    'apps.dashboard',
    'apps.frontend',
    'apps.blog',
    'apps.worker',
    'apps.patient',
    'apps.schedule',
    'apps.service',

]

WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": "BOmjqkGL3xAwzVxr_35TA9onNEYtxb5218VDFcyx3i5LL57Rt04ZQw88W5J03WVehH9-rEivWh3iXq_KYVzTbGE",
    "VAPID_PRIVATE_KEY":"m-bUNZyo48cgvLrlkNY_-VAmpn6PLjp4owJm7oP9VAo",
    "VAPID_ADMIN_EMAIL": "admin@alento.com"
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.layout_blocks'
            ],
            'libraries':{
                'model_tags': 'core.templatetags.model_tags',
                'custom_filters': 'core.templatetags.custom_filters',

            }
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
         'ENGINE': 'django.db.backends.mysql',
         'HOST': os.environ.get['DATABASE_HOST'],
         'NAME': os.environ.get['DATABASE_NAME'],
         'PORT': int(os.environ.get['DATABASE_PORT']),
         'USER': os.environ.get['DATABASE_USER'],
         'PASSWORD': os.environ.get['DATABASE_PASS'],
         'OPTIONS': {
             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'", }
    }
}

sdsfd sdas asda
# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'gl'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "public_html", "static")
STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "assets"),
    os.path.join(BASE_DIR, "static")
)
# STATICFILES_DIRS = [BASE_DIR / 'assets', BASE_DIR / 'static']
# STATIC_ROOT = BASE_DIR / 'staticroot'

# Media files
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / "media"
MODELTRANSLATION_DEFAULT_LANGUAGE = 'gl'
MODELTRANSLATION_FALLBACK_LANGUAGES = ('gl', 'es', 'pt', 'en')

LANGUAGES = [
    ('gl', _('galician')),
    ('es', _('spanish')),
    ('pt', _('portuguese')),
    ('en', _('english')),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale')
]

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Admin
SITE_HEADER = os.environ.get['SITE_HEADER']
SITE_TITLE = os.environ.get['SITE_TITLE']
INDEX_TITLE = os.environ.get['INDEX_TITLE']


THUMBNAIL_ALIASES = {
    '': {
        '850w': {'size': (850, 350), 'crop': True},
        '90w': {'size': (90, 90), 'crop': True},
         },
}

LEAFLET_CONFIG = {
    # 'DEFAULT_CENTER': (41.9074666, -8.865225900000041),
    'DEFAULT_ZOOM': 13,
    'MIN_ZOOM': 3,
    'MAX_ZOOM': 18,
}

if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend',
    EMAIL_HOST = os.environ.get['EMAIL_HOST'],
    EMAIL_PORT = os.environ.get['EMAIL_PORT'],
    EMAIL_HOST_USER = os.environ.get['EMAIL_HOST_USER'],
    EMAIL_HOST_PASSWORD = os.environ.get['DEFAULT_FROM_EMAIL'],
    EMAIL_USE_TLS = False
    EMAIL_USE_SSL = True


SUMMERNOTE_CONFIG = {
    # Using SummernoteWidget - iframe mode, default
    'iframe': True,

    # You can put custom Summernote settings
    'summernote': {
        # As an example, using Summernote Air-mode
        'airMode': False,

        # Change editor size
        'width': '100%',
        'height': '480',

        # Use proper language setting automatically (default)
        'lang': None,
    }
}
