# Generated by Django 2.2.7 on 2019-12-26 14:53

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=False, verbose_name='active_status')),
                ('date_active_ini', models.DateField(blank=True, null=True, verbose_name='date ini')),
                ('date_active_end', models.DateField(blank=True, null=True, verbose_name='date end')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='name')),
                ('name_es', models.CharField(blank=True, max_length=200, null=True, verbose_name='name')),
                ('name_gl', models.CharField(blank=True, max_length=200, null=True, verbose_name='name')),
                ('name_pt', models.CharField(blank=True, max_length=200, null=True, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='name')),
                ('description_short', models.TextField(blank=True, null=True, verbose_name='description short')),
                ('description_short_es', models.TextField(blank=True, null=True, verbose_name='description short')),
                ('description_short_gl', models.TextField(blank=True, null=True, verbose_name='description short')),
                ('description_short_pt', models.TextField(blank=True, null=True, verbose_name='description short')),
                ('description_short_en', models.TextField(blank=True, null=True, verbose_name='description short')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogcategory/', verbose_name='image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=False, verbose_name='active_status')),
                ('date_active_ini', models.DateField(blank=True, null=True, verbose_name='date ini')),
                ('date_active_end', models.DateField(blank=True, null=True, verbose_name='date end')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('publication_status', models.CharField(choices=[('f', 'Form Draft'), ('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn')], default='d', max_length=1, verbose_name='publication status')),
                ('slug', models.SlugField(max_length=200, null=True, unique=True, verbose_name='slug')),
                ('slug_es', models.SlugField(max_length=200, null=True, unique=True, verbose_name='slug')),
                ('slug_gl', models.SlugField(max_length=200, null=True, unique=True, verbose_name='slug')),
                ('slug_pt', models.SlugField(max_length=200, null=True, unique=True, verbose_name='slug')),
                ('slug_en', models.SlugField(max_length=200, null=True, unique=True, verbose_name='slug')),
                ('author', models.CharField(blank=True, max_length=200, null=True, verbose_name='author')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('title_es', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('title_gl', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('title_pt', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('description_short', models.TextField(blank=True, null=True, verbose_name='description short')),
                ('description_short_es', models.TextField(blank=True, null=True, verbose_name='description short')),
                ('description_short_gl', models.TextField(blank=True, null=True, verbose_name='description short')),
                ('description_short_pt', models.TextField(blank=True, null=True, verbose_name='description short')),
                ('description_short_en', models.TextField(blank=True, null=True, verbose_name='description short')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_gl', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_pt', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, max_length=200, null=True, verbose_name='icon')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='blog/', verbose_name='imagen section')),
                ('image_bg', models.ImageField(blank=True, default='blog/bg_1.jpg', null=True, upload_to='blog/', verbose_name='background-image blog')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='subtitle')),
                ('subtitle_es', models.CharField(blank=True, max_length=200, null=True, verbose_name='subtitle')),
                ('subtitle_gl', models.CharField(blank=True, max_length=200, null=True, verbose_name='subtitle')),
                ('subtitle_pt', models.CharField(blank=True, max_length=200, null=True, verbose_name='subtitle')),
                ('subtitle_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='subtitle')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='blog.BlogCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
