# Generated by Django 2.2.7 on 2019-12-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.TextField(blank=True, default=1, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='description_short',
            field=models.TextField(blank=True, default=1, verbose_name='description short'),
            preserve_default=False,
        ),
    ]
