# Generated by Django 2.2.6 on 2019-12-29 22:35

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191226_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image_bg',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='name_image',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='name image'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='blog/', verbose_name='image'),
        ),
    ]
