# Generated by Django 2.2.6 on 2019-12-29 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191229_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='expired_at',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='publication_status',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='published_at',
        ),
    ]
