# Generated by Django 2.2.6 on 2019-12-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191230_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='meta_description'),
        ),
    ]
