# Generated by Django 2.2.6 on 2019-12-30 02:12

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191230_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='blog/default.jpg', upload_to='blog/', verbose_name='image'),
        ),
    ]
