# Generated by Django 2.2.6 on 2019-12-27 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='worker/default.png', upload_to='worker/', verbose_name='image')),
                ('passwd', models.CharField(blank=True, default='', max_length=100, verbose_name='password')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='address')),
                ('postalcode', models.CharField(blank=True, max_length=100, verbose_name='postalcode')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='state')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='country')),
                ('phone1', models.CharField(blank=True, max_length=100, verbose_name='phone 1')),
                ('phone2', models.CharField(blank=True, max_length=100, verbose_name='phone 2')),
                ('email1', models.EmailField(blank=True, max_length=100, verbose_name='email 1')),
                ('email2', models.EmailField(blank=True, max_length=100, verbose_name='email 2')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='contact name')),
                ('contact_phone', models.CharField(blank=True, max_length=100, verbose_name='contact phone')),
                ('contact_email', models.EmailField(blank=True, max_length=100, verbose_name='contact email')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note to parter')),
                ('private_comment', models.TextField(blank=True, null=True, verbose_name='private comment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
