# Generated by Django 2.2.6 on 2019-12-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_auto_20191228_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='active',
        ),
        migrations.AddField(
            model_name='worker',
            name='active_status',
            field=models.BooleanField(default=False, verbose_name='active_status'),
        ),
        migrations.AddField(
            model_name='worker',
            name='date_active_end',
            field=models.DateField(blank=True, null=True, verbose_name='date end'),
        ),
        migrations.AddField(
            model_name='worker',
            name='date_active_ini',
            field=models.DateField(blank=True, null=True, verbose_name='date ini'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone1',
            field=models.CharField(blank=True, max_length=100, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone2',
            field=models.CharField(blank=True, max_length=100, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='postalcode',
            field=models.CharField(blank=True, max_length=100, verbose_name='postal code'),
        ),
    ]
