# Generated by Django 2.2.6 on 2020-01-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_auto_20200101_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='dni',
            field=models.CharField(default=1, max_length=9, unique=True, verbose_name='dni'),
            preserve_default=False,
        ),
    ]
