# Generated by Django 2.2.6 on 2020-01-01 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20200101_0353'),
        ('worker', '0006_auto_20200101_0331'),
        ('schedule', '0002_auto_20200101_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='patient.Patient', verbose_name='patient'),
        ),
        migrations.AddField(
            model_name='event',
            name='worker',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='worker.Worker', verbose_name='worker'),
        ),
    ]
