# Generated by Django 2.2.6 on 2020-01-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20200101_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='service',
            field=models.CharField(choices=[('ds', 'personal and domestic services'), ('cs', 'complementary services'), ('ts', 'therapeutic service'), ('od', 'other service')], default='', max_length=200, verbose_name='service'),
        ),
    ]
