# Generated by Django 2.2.6 on 2020-01-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20200101_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(help_text='end hour of the event', verbose_name='end hour of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(help_text='hour of the event', verbose_name='hour of the event'),
        ),
    ]
