# Generated by Django 2.2.6 on 2020-01-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
    ]
