# Generated by Django 2.2.6 on 2020-01-01 02:24

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worker', '0005_auto_20191228_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=False, verbose_name='active_status')),
                ('date_active_ini', models.DateField(blank=True, null=True, verbose_name='date ini')),
                ('date_active_end', models.DateField(blank=True, null=True, verbose_name='date end')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='patient/default.png', upload_to='patient/', verbose_name='image')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='last name')),
                ('dni', models.CharField(blank=True, max_length=9, verbose_name='dni')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='address')),
                ('postalcode', models.CharField(blank=True, max_length=100, verbose_name='postal code')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='state')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='country')),
                ('phone1', models.CharField(blank=True, max_length=100, verbose_name='phone')),
                ('phone2', models.CharField(blank=True, max_length=100, verbose_name='phone')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='contact name')),
                ('contact_phone', models.CharField(blank=True, max_length=100, verbose_name='contact phone')),
                ('contact_email', models.EmailField(blank=True, max_length=100, verbose_name='contact email')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note to parter')),
                ('private_comment', models.TextField(blank=True, null=True, verbose_name='private comment')),
                ('worker', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='worker.Worker', verbose_name='worker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
