# Generated by Django 2.2.6 on 2020-01-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20200101_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dni',
            field=models.CharField(max_length=9, verbose_name='dni'),
        ),
    ]
