# Generated by Django 2.2.6 on 2020-01-01 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20200101_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='worker.Worker', verbose_name='worker'),
        ),
    ]
