# Generated by Django 2.2.6 on 2020-01-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20200101_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dni',
            field=models.CharField(max_length=9, unique=True, verbose_name='dni'),
        ),
    ]
