# Generated by Django 2.2.6 on 2020-01-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20200101_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='', max_length=120, verbose_name='email'),
        ),
    ]
