# Generated by Django 2.2.6 on 2020-01-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='patient',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, verbose_name='longitude'),
        ),
    ]
