# Generated by Django 2.2.4 on 2019-08-25 10:46

import apps.income.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('date_payment', models.DateField(blank=True, null=True, verbose_name='date payment')),
                ('invoice_number', models.CharField(blank=True, default='', max_length=50, verbose_name='invoice number')),
                ('total', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='total')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='comment')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='incomes/', validators=[apps.income.models.validate_report_extension], verbose_name='invoice file')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
