# Generated by Django 2.2.4 on 2019-11-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_auto_20190919_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='user',
            field=models.CharField(blank=True, default=1, max_length=120, verbose_name='user'),
            preserve_default=False,
        ),
    ]
