# Generated by Django 2.2.4 on 2019-11-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0005_auto_20191113_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='local',
            field=models.CharField(blank=True, max_length=120, verbose_name='local'),
        ),
    ]
