# Generated by Django 2.2.6 on 2020-01-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0007_income_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='total',
            field=models.DecimalField(decimal_places=6, max_digits=20, verbose_name='total'),
        ),
    ]
