# Generated by Django 2.2.7 on 2019-12-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorylink',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='categorylink',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='categorylink',
            name='description_gl',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='categorylink',
            name='description_pt',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='categorylink',
            name='description_short_en',
            field=models.TextField(blank=True, null=True, verbose_name='description short'),
        ),
        migrations.AddField(
            model_name='categorylink',
            name='description_short_es',
            field=models.TextField(blank=True, null=True, verbose_name='description short'),
        ),
        migrations.AddField(
            model_name='categorylink',
            name='description_short_gl',
            field=models.TextField(blank=True, null=True, verbose_name='description short'),
        ),
        migrations.AddField(
            model_name='categorylink',
            name='description_short_pt',
            field=models.TextField(blank=True, null=True, verbose_name='description short'),
        ),
        migrations.AddField(
            model_name='categorylink',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='categorylink',
            name='name_es',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='categorylink',
            name='name_gl',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='categorylink',
            name='name_pt',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='link',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='link',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='link',
            name='description_gl',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='link',
            name='description_pt',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='link',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='link',
            name='name_es',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='link',
            name='name_gl',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='link',
            name='name_pt',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='name'),
        ),
    ]
