# Generated by Django 2.2.7 on 2019-12-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20191225_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, max_length=40, verbose_name='latitude')),
                ('longitude', models.CharField(blank=True, max_length=40, verbose_name='longitude')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='name')),
                ('email', models.CharField(blank=True, max_length=40, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=40, null=True, verbose_name='phone')),
                ('address', models.CharField(blank=True, max_length=40, null=True, verbose_name='address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
