# Generated by Django 2.2.7 on 2019-12-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_contact_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=False, verbose_name='active_status')),
                ('date_active_ini', models.DateField(blank=True, null=True, verbose_name='date ini')),
                ('date_active_end', models.DateField(blank=True, null=True, verbose_name='date end')),
                ('name', models.CharField(blank=True, choices=[('fi-web', 'Whatsapp'), ('fi-social-facebook', 'Facebbok'), ('fi-social-instagram', 'Instagram'), ('fi-social-twitter', 'Twitter'), ('fi-social-pinterest', 'Pinterest'), ('fi-social-google-plus', 'Google'), ('fi-social-linkedin', 'Linkedin')], max_length=160, verbose_name='network')),
                ('url', models.CharField(blank=True, max_length=160, verbose_name='url')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
