# Generated by Django 2.2.6 on 2019-12-28 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link', to='frontend.CategoryLink', verbose_name='category'),
        ),
    ]
