# Generated by Django 2.2.6 on 2019-12-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_link_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylink',
            name='hook',
            field=models.CharField(blank=True, choices=[('hf', 'home frontend'), ('ff', 'footer frontend'), ('hd', 'home dashboard'), ('fd', 'footer dashboard')], default='', max_length=200, null=True, unique=True, verbose_name='hook'),
        ),
        migrations.AlterField(
            model_name='link',
            name='hook',
            field=models.CharField(blank=True, choices=[('hf', 'home frontend'), ('ff', 'footer frontend'), ('hd', 'home dashboard'), ('fd', 'footer dashboard')], default='', max_length=200, null=True, unique=True, verbose_name='hook'),
        ),
    ]
