# Generated by Django 2.2.6 on 2019-12-31 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20191229_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='address',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='phone',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='link',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link', to='frontend.CategoryLink', verbose_name='categoría'),
        ),
        migrations.AlterField(
            model_name='link',
            name='icon',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='icono'),
        ),
    ]
