# Generated by Django 2.2.6 on 2020-01-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20191231_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='url'),
        ),
    ]
