# Generated by Django 2.2.6 on 2020-01-13 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20200101_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='address',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='phone',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='link',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link', to='frontend.CategoryLink', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='link',
            name='icon',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='icon'),
        ),
    ]
