# Generated by Django 2.2.6 on 2020-01-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20200113_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='name',
            field=models.CharField(blank=True, choices=[('fa fa-facebook', 'Facebbok'), ('fa fa-instagram', 'Instagram'), ('fa fa-twitter', 'Twitter'), ('fa fa-pinterest-square', 'Pinterest'), ('fa fa-google-plus', 'Google'), ('fa fa-linkedin', 'Linkedin')], max_length=160, verbose_name='network'),
        ),
    ]
