# Generated by Django 2.2.4 on 2019-11-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_auto_20190919_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='operador',
            field=models.CharField(blank=True, max_length=200, verbose_name='operador'),
        ),
    ]
