# Generated by Django 2.2.4 on 2019-11-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_expense_operador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='operador',
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.CharField(blank=True, default=1, max_length=120, verbose_name='user'),
            preserve_default=False,
        ),
    ]
