# Generated by Django 2.2.4 on 2019-11-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0009_auto_20191114_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='machine',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='machine'),
        ),
    ]
